package Switch;

import java.util.Random;

public class Switch {

    private static String[] switchList = {
            "Remove Duplicates from Sorted Array I",
            "Remove Duplicates from Sorted Array II",
            "Remove Element",
            "Move Zeroes",
            "Candy",
            "Trapping Rain Water",
            "Product of Array Except Self",
            "Minimum Size Subarray Sum",
            "Summary Ranges",
            "Missing Ranges",
            "Merge Intervals",
            "Insert Interval",
            "Partition Labels",
            "Find And Replace in String",
            "My Calendar II",
            "One Edit Distance",
            "Merge Sorted Array",
            "Is Subsequence",
            "Backspace String Compare",
            "Repeated String Match",
            "Container With Most Water",
            "Reverse Vowels of a String",
            "Valid Palindrome",
            "Shortest Word Distance",
            "Shortest Word Distance II",
            "Shortest Word Distance III",
            "Intersection of Two Arrays",
            "Intersection of Two Arrays II",
            "Two Sum II",
            "Two Sum III",
            "3Sum",
            "4Sum",
            "3Sum Closest",
            "Wiggle Sort",
            "Wiggle subsequence",
            "Longest Common Prefix",
            "Next permutation",
            "Sentence Screen Fitting",
            "Search Insert Position",
            "Median of Two Sorted Arrays",
            "Find Minimum in Rotated Sorted Array: I",
            "Find First and Last Position of Element in Sorted Array ",
            "Find Minimum in Rotated Sorted Array: II",
            "Guess Number Higher or Lower",
            "First Bad Version",
            "Search in Rotated Array:I",
            "Search in Rotated Array: II",
            "Longest Increasing Subsequence",
            "Count of Smaller Numbers After Self",
            "Russian Doll Envelopes",
            "H-Index",
            "H-Index II",
            "Valid Anagram",
            "Group Shifted Strings",
            "Palindrome Pairs",
            "Line Reflection",
            "Isomorphic Strings",
            "Two Sum",
            "Maximum Size Subarray Sum Equals k",
            "Subarray Sum Equals K",
            "Longest Substring Without Repeating Characters",
            "Longest Substring that contains k unique characters",
            "Substring with Concatenation of All Words",
            "Minimum Window Substring",
            "Longest Substring with At Least K Repeating Characters",
            "Permutation in String",
            "Longest Consecutive Sequence",
            "Majority Element: I, II",
            "Increasing Triplet Subsequence",
            "Find the 2nd Largest Elements in an array",
            "Word Ladder (BFS), Word Ladder II (BFS)",
            "Top K Frequent Elements",
            "Meeting Rooms II, Meeting Rooms",
            "Range Addition",
            "Merge k sorted arrays",
            "Merge k Sorted Lists",
            "Rearrange String k Distance Apart",
            "Minimum Cost to Hire K Workers",
            "Contains Duplicate: I, II, III",
            "Max Sum of Rectangle No Larger Than K",
            "Maximum Sum Of Subarray Close To K",
            "K Empty Slots",
            "Sliding Window Maximum",
            "Moving Average from Data Stream",
            "Find Median from Data Stream",
            "Data Stream as Disjoint Intervals",
            "Streaming random: Linked List Random Node, Shuffle an Array",
            "Mergesort",
            "Quicksort, Kth Largest Element in an Array",
            "Sort Colors (Counting Sort)",
            "Maximum Gap (Bucket Sort)",
            "Group Anagrams (Bucket Sort)",
            "Ugly Number, Ugly Number II",
            "Super Ugly Number",
            "Find K Pairs with Smallest Sums from two arrays",
            "Rotate Array, Reverse Words in a String",
            "Missing Number",
            "Find the duplicate number",
            "First Missing Positive",
            "Queue Reconstruction by Height",
            "Binary Watch",
            "Next Closest Time"
    };

    public static void main(String[] args) {
        Random random = new Random();
        System.out.println(switchList[random.nextInt(switchList.length)]);
    }
}
